server:
  port: 8081

person:
  name: fugui
  age: 3
  happy: false
  birth: 2020/06/26
  maps: {k1: v1, k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: fugui
    age: 3

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#
mybatis:
  type-aliases-package: com.nkong.bean
  mapper-locations: classpath:mybatis/mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

swagger:
  enable: false